CREATE TABLE dbo.Holidays (
	id int IDENTITY (1,1) NOT NULL
,	Date date NOT NULL
) ON [PRIMARY]
GO 

CREATE TABLE dbo.DateDim (
	id bigint NOT NULL
,	Today date NOT NULL
,	BusinessDate date NOT NULL
,	[Index] int NOT NULL
,	CONSTRAINT PK_DateDim PRIMARY KEY CLUSTERED(id ASC) 
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]
) ON [PRIMARY]
GO